POST http://localhost:8080/polls/
Content-Type: application/json

{
  "title": "Pizza preference",
  "question": {
    "question_text": "Do you hate pizza?",
    "pollOptions": [
      { "text": "yes" },
      { "text": "no" }
    ]
  }
}
