### Get CSRF
# @name csrf
GET http://localhost:8080/polling/backend/auth/csrf

### Create poll (send BOTH header and cookie)
POST http://localhost:8080/polling/backend/polls
Content-Type: application/json
X-XSRF-TOKEN: {{csrf.response.body.token}}
Cookie: XSRF-TOKEN={{csrf.response.body.token}}


{
  "title": "Pizza preference",
  "question": "Do you hate pizza?",
  "voteOptions": [
      { "caption": "yes",
       "presentationOrder": 1 
     },
      { "caption": "no", 
       "presentationOrder": 2}
    ],
  "creator": "Magnus"
}  


{
  "question": "",
  "voteOptions": {
    "pollOptions": [
      {
        "caption": "Vote"
      }
    ]
  }
}
