POST http://localhost:8080/polls
Content-Type: application/json

{
  "title": "Pizza preference",
  "question": "Do you hate pizza?",
  "voteOptions": [
      { "caption": "yes",
       "presentationOrder": 1 
     },
      { "caption": "no", 
       "presentationOrder": 2}
    ],
  "creator": "Magnus"
}  


{
  "question": "",
  "voteOptions": {
    "pollOptions": [
      {
        "caption": "Vote"
      }
    ]
  }
}
