POST http://localhost:8080/test/poll
Content-Type: application/json

{
  "title": "Pizza preference",
  "question": "Do you hate pizza?",
  "voteOptions": [
      { "caption": "yes" },
      { "caption": "no" }
  ],
  "creator": {"userName": "Magnus"}
    ,
  "pollID" : 1
}
