@startuml Architechture

node "External\nClients" as mu
interface HTTPS
node "PollService" {
component "Caddy" as caddy
component "Web UI\n(React)" as ui
interface HTTP
component "REST API\n(Spring Web MVC)" as api

caddy -right-HTTPS
caddy -down- ui
api -up- HTTP
HTTP -right- caddy
component "Business Logic(Poll Manager)" as dom
component "Persistence\n(JPA H2)" as per
database H2
api -down-> dom
dom -down-> per
per -down-> H2
}
database "Redis" as redis


queue "RabbitMQ" as msg
dom --> msg : messaging
api -left-> redis : vote-cache

actor "End Users"  as ru
HTTPS <.> ru  
mu <.down.> caddy
mu .> msg
@enduml
