@startuml Architechture

node "External\nClients" as mu
node "PollService" {
node "Nginx" as nginx
component "Web UI\n(React)" as ui
interface HTTP
component "REST API\n(Spring Web MVC)" as api

api -up- HTTP
HTTP -right- nginx
component "Business Logic(Poll Manager)" as dom
component "Persistence\n(JPA H2)" as per
database H2
api -down-> dom
dom -down-> per
per -down-> H2
}
database "Redis" as redis


queue "RabbitMQ" as msg
dom --> msg : messaging
api -left-> redis : vote-cache

actor "End Users"  as ru
nginx <.> ru  
ui <.> nginx 
mu <.down.> nginx
mu .> msg
@enduml